# Generated by Django 4.1 on 2024-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMA', '0003_remove_task_name_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
